---
title: "Untitled"
author: "team"
output: pdf_document
---
Gibb sampling Inverse tranform jujari

Provided the conditional probabilities $p(x|y) \propto exp(Y)$ and $p(y|x) \propto exp(X)$, we want to generate the samples from the conditional distributions. 

Since conditional distribution of $X|Y$ and $Y|X$ are equivalent in a sense that both follows the exponential distribution with rate parameter of one another. 

Also note that the support of an exponential distirubtion is $[0,\infty]$, but the conditional distribution have the support $[0,B]$ so we need to adjust for the ¡°right end¡± when going through inverse transform to generate the random numbers of our interst using uniform distribution.

We may find the conditional density of $X|Y$ or $Y|X$ and the find conditional cumulative distribution function, inverse of which can be used to draw random samples.

Additionally we may solve for the end point of the unifrom distribution i.e. $B$ such that $F_{x}^{-1}(z)\in[0,B]$.

Given the cumulative distirubtion function of an exponential distribution $F_{x}(z)=1-e^{-yz}$, the quantile function (inverse cdf) is $F_{x}^{-1}(z)=-\frac{1}{y}log(1-z)$

Then, consider the following. Let $B=-\frac{1}{y}log(1-z)$ and solving for $z$ gives $z=1-e^{-yB}=F_{x}(B)$

Thus. >qexp(runif(1, 0, pexp(B, lambda)), lambda) returns the random number from the conditional distribution.
 